//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenemeProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int ID { get; set; }
        public string AvatarURL { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> ContactPhone { get; set; }
        public string EmailAddess { get; set; }
        public string CompanySite { get; set; }
    }
}
